### ISSUE TITLE
Order status is not getting updated - as the Payment changes from "authorized" to "captured"

### ISSUE THREAD

**Issue by osmarghyadeep** [razorpay/razorpay-python#132] opened 2021-04-15 16:56 UTC
Assumption - As soon as the status of the payment changes from "authorized" to "captured" - the respective order status should update automatically from "created" to "attempted" or "paid"

Nothing is happening according to this assumption!!

(Please correct me if I am wrong here in my "Assumption")

I was working in "test" environment

**Comment by ankitdas13** [comment] 2022-11-23 12:06
@osmarghyadeep Apologise for the long delay. The order status should be changed to "paid" after payment got captured. If it's not happened, then it might be possible there are some technical issues .  Since we don't see any users experiencing this issue, could you please double check it once and let us know?

**Comment by ankitdas13** [comment] 2023-01-23 07:19
Closing this issue due to not getting any response. Please re-open this issue if the issue is still persisting. Let me know if you need any help.

**Closed by ankitdas13** 2023-01-23 07:19 UTC
Labels: awaiting response
