### ISSUE TITLE
SERVER_ERROR

### ISSUE THREAD

**Issue by siddanand** [razorpay/razorpay-python#88] opened 2020-07-10 19:55 UTC
while creating a fund account during a payout i am getting a server error, how can i solve it

**Comment by ankitdas13** [comment] 2022-11-24 11:58
Duplicate of #89

**Comment by ankitdas13** [comment] 2023-01-18 06:55
Closing this issue for now, due to not getting any response. If you need help then please let us know

**Closed by ankitdas13** 2023-01-18 06:55 UTC
Labels: duplicate
