### ISSUE TITLE
Compatibility with urllib3 1.26.0

### ISSUE THREAD

**Issue by Mitalee** [razorpay/razorpay-python#120] opened 2020-11-11 12:43 UTC
Razorpay calls are failing with the latest version of urllib3 (1.26.0, released on 11/11, https://pypi.org/project/urllib3/#history)

```python
root@07:/app# pipdeptree -r -p razorpay
Warning!!! Possibly conflicting dependencies found:
* requests==2.24.0
 - urllib3 [required: >=1.21.1,<1.26,!=1.25.1,!=1.25.0, installed: 1.26.0]
------------------------------------------------------------------------
razorpay==1.2.0
```

**Comment by Mitalee** [comment] 2020-11-12 05:04
Hi guys, for now I have found that pip allows installation with a 2020 resolver. The following has fixed the issue temporarily:
```bash
pip install razorpay --use-feature=2020-resolver
```

**Comment by ankitdas13** [comment] 2022-11-23 14:12
@Mitalee Apologise for the long delay. Would you please let me know if this issue has affected the SDK?

**Comment by ankitdas13** [comment] 2023-01-23 07:22
Closing this issue due to not getting any response. Please re-open this issue if the issue is still persisting. Let me know if you need any help.

**Closed by ankitdas13** 2023-01-23 07:22 UTC
Labels: awaiting response
