### ISSUE TITLE
Payments are not auto captured

### ISSUE THREAD

**Issue by osmarghyadeep** [razorpay/razorpay-python#131] opened 2021-04-15 16:52 UTC
So suppose we created an order -> order_a (state: created)
Also we did the payment -> payment_a (state: authorized)

Auto capturing of payments is turned on.

Issue 1: Payments are not auto captured - not sure why
As of now - we have a work around - we are explicitly calling the api to capture the payment

But still this is an issue as --
- Is the feature meant to be deprecated, or 
- There is really an issue

I was working in test environment

**Comment by ankitdas13** [comment] 2022-11-23 12:21
Duplicate of #132

**Comment by ankitdas13** [comment] 2023-01-23 07:26
Closing this issue because this issue is duplicate of #132 and we don't got any response also the issue is not related to the sdk.

**Closed by ankitdas13** 2023-01-23 07:26 UTC
Labels: duplicate
