### ISSUE TITLE
Callback URL not formatted properly

### ISSUE THREAD

**Issue by toppertemple** [razorpay/razorpay-python#101] opened 2020-08-04 08:43 UTC
I am appending GET params in callback URL but the razorpay invoice generated short-url is not formatted properly
Example:
needed: https://www.example.com/response?param=example&razorpay_payment_id=example........
getting: https://www.example.com/response?param=example?razorpay_payment_id=example........

**Comment by ankitdas13** [comment] 2022-11-24 11:40
@toppertemple Could you please let us know if this issue has been resolved. If not then it would be helpfull if you explain me more about this issue so we can replicate this from our end but if it was resolved then , please close it

**Comment by ankitdas13** [comment] 2023-01-19 08:51
Closing this issue for now, due to not getting any response. Please don't let that stop you from re-opening if the issue is persisting for you. Let us know if you need any help.

**Closed by ankitdas13** 2023-01-19 08:51 UTC
Labels: awaiting response
